name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega desde la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build  # Asegúrate de que tu proyecto tenga un script 'build' en package.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # La carpeta de salida de tu proyecto
